vich_uploader:
    db_driver: orm

    mappings:
        media_images:
            uri_prefix: '%media_images%'
            upload_destination: '%kernel.project_dir%/public/%media_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
